### ISSUE TITLE
Experiment: Also make subgroups from tag groups.

### ISSUE THREAD

**Issue by nsg** [nsg/ansible-inventory#11]
``` yml

groups:
  foo:
    - bar
```

This will give us `root`, `root-foo` and the tag group `bar` today.

Try to expand this to `bar` also is a subgroup under `root-foo`:

`root`, `root-foo`, `root-foo-bar` and the tag group `bar`.
