### ISSUE TITLE
Fix children

### ISSUE THREAD

**Issue by nsg** [nsg/ansible-inventory#5]
Buggy when we have something like:

``` yml
groups:
  foo:
    bar:
      - host1
      - host2
  baz:
    bar:
      - host3
```

this creates a `foo:children => bar` and `baz:children => bar` relation that confuses Ansible. Replace this with the "long full group names". For example `foo:children => foo-bar`.
