### ISSUE TITLE
Support list and dicts under vars

### ISSUE THREAD

**Issue by nsg** [nsg/ansible-inventory#6]
Something like this would be nice:

``` yaml

vars:
  mygroup:
    foo:
      - name: kaka
        foo: bar
```

=> Run the full yaml parser on dicts (assume old key=value syntax if there is a list here).
