### ISSUE TITLE
Change format

### ISSUE THREAD

**Issue by nsg** [nsg/ansible-inventory#7]
I will change the format from:

``` yml
groups:
  site:
    www:
      - host1
      - name: host2
        vars:
          - bar=1

vars:
  site:
    - foo=bar
```

to

``` yml
groups:
  site:
    www:
      - host1
      - name: host2
        bar: 1
  vars:
      foo: bar
```
